return {
	--
	-- "milanglacier/minuet-ai.nvim",
	-- version = "*",
	-- config = function()
	-- 	require("minuet").setup({
	-- 		provider = "openai_fim_compatible",
	-- 		blink = {
	-- 			enable_auto_complete = true,
	-- 			enable_context,
	-- 		},
	-- 		virtualtext = {
	-- 			auto_trigger_ft = {
	-- 				"lua",
	-- 				"python",
	-- 				"javascript",
	-- 				"typescript",
	-- 				"tsx",
	-- 				"go",
	-- 				"dart",
	-- 				"rust",
	-- 				"cpp",
	-- 				"c",
	-- 				"vim",
	-- 				"markdown",
	-- 				"yaml",
	-- 				"json",
	-- 				"toml",
	-- 				"dockerfile",
	-- 				"html",
	-- 				"css",
	-- 				"sql",
	-- 				"bash",
	-- 				"gitignore",
	-- 			},
	-- 			keymap = {
	-- 				accept = "<C-CR>",
	-- 				accept_line = "<C-l>",
	-- 				accept_n_lines = "<M-z>",
	-- 				prev = "<C-k>",
	-- 				next = "<C-j>",
	-- 				dismiss = "<C-e>",
	-- 			},
	-- 		},
	-- 		n_completions = 1,
	-- 		context_window = 1500,
	-- 		throttle = 400,
	-- 		debounce = 100,
	-- 		request_timeout = 10,
	-- 		provider_options = {
	-- 			openai_fim_compatible = {
	-- 				end_point = "http://localhost:1234/v1/completions",
	-- 				model = "deepseek-coder-1.3b-base",
	-- 				api_key = "TERM",
	-- 				name = "LMStudio",
	-- 				stream = true,
	-- 				template = {
	-- 					prompt = function(context_before_cursor, _, _)
	-- 						return "<|fim_begin|>" .. context_before_cursor
	-- 					end,
	-- 					suffix = function(_, context_after_cursor, _)
	-- 						return context_after_cursor .. "<|fim_end|>"
	-- 					end,
	-- 				},
	-- 				optional = {
	-- 					max_tokens = 128,
	-- 					top_p = 0.9,
	-- 					thinking = { type = "disabled" },
	-- 				},
	-- 			},
	-- 		},
	-- 	})
	-- end,
}
